---
- hosts: k8s
  become: true
  tasks:
    - name: Install docker and its dependencies
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: no
      vars:
        packages:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io
      notify:
        - docker status
        
    - name: Add vagrant user to docker group
      user:
        name: vagrant
        group: docker

    - name: Install Kubernetes binaries
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: no
      vars:
        packages:
          - kubelet 
          - kubeadm 
          - kubectl
  
    - name: Configure node ip
      lineinfile:
        create: yes
        path: /etc/default/kubelet
        line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

    - name: Ensure kubelet is started and enabled at boot.
      service:
        name: kubelet
        state: started
        enabled: true
    
    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted

  handlers:
    - import_tasks: handlers/docker.yml
